[package]
name = "rust-scratch-pad"
version = "0.1.0-SNAPSHOT"
authors = ["Alex Michael Berry <berry3@indiana.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = "0.14.0"
rand = "0.7"
sled = "0.31.0"
